---
title: 
author:
output:
  pdf_document: 
    number_sections: true
    extra_dependencies: ["polski", "mathtools", "amsthm", "amssymb", "icomma", "upgreek", "xfrac", "scrextend", "float", "tabularx", "hyperref", "caption", "enumitem", "titlesec"]
fontsize: 12pt
---


\renewcommand{\figurename}{Wykres}
\renewcommand{\tablename}{Tablica}
\raggedbottom
\titlelabel{\thetitle.\quad}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, eval = TRUE, fig.pos = "H", dev.args=list(encoding="CP1257.enc"))
library(reticulate)
path <- readLines("python_path.txt")
use_python(path)
```


```{python}
from sqlalchemy import create_engine, MetaData, Table, text
from sqlalchemy.orm import sessionmaker
from urllib.parse import quote

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as sp
from datetime import datetime

import warnings
warnings.filterwarnings('ignore')

today = str(datetime.today().date())

username = 'team25'
password = quote('te@mzs')
database = 'team25'
host = 'giniewicz.it'
port = '3306'

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

metadata = MetaData()
games_for_sale = Table('games_for_sale', metadata, autoload_with = engine)
games_to_rent = Table('games_to_rent', metadata, autoload_with = engine)
customers = Table('customers', metadata, autoload_with = engine)
staff = Table('staff', metadata, autoload_with = engine)
sale = Table('sale', metadata, autoload_with = engine)
rental = Table('rental', metadata, autoload_with = engine)
competition = Table('competition', metadata, autoload_with = engine)
competition_results = Table('competition_results', metadata, autoload_with = engine)

connection = engine.connect()
```

```{python}
# Przydatne funkcje

def query_to_df(sql):
    result = connection.execute(text(sql))
    df = pd.DataFrame(result.fetchall(), columns=result.keys())
    return df
```




\title{ \Large \textsc{Bazy danych}
		\\ [5.5cm]
		\LARGE \textbf{\uppercase{Analiza danych i raport}}
		%\\ [0.5cm]
		%\normalsize \today \vspace*{20\baselineskip}
		}
	\date{}
	\maketitle
	\vspace{7cm}
	
\begin{center}
\author{
  Szymon Malec, 262276 \\
  Adam Wrzesiński, 262317\\
  Michał Wiktorowski, 262330 \\
  Weronika Zmyślona, 262284 \\
  \vspace{0.5cm}
  Politechnika Wrocławska \\
  Wydział Matematyki - Matematyka Stosowana}
\end{center}

\thispagestyle{empty}

\newpage\thispagestyle{empty}
\mbox{}

\setcounter {page}{1}

\tableofcontents

\newpage





\section{Wstęp}

|       Raport pełni funkcję podsumowującą dane dostepne w bazie sklepu Geeks and Dragons za pomocą wizualizacji i podstawowych statystyk. W dalszej części znajdują się rozwiązania nastepujących zagadnień i pytań:
\begin{itemize}
  \item Ranking na pracownika miesiąca.
  \item Ranking zawodników turniejowych.
  \item Które gry przynoszą największy dochód ze sprzedaży, a które z wypożyczeń?
  \item Które kategorie są najpopularniejsze?
  \item Jak zmieniała się sprzedaż na przestrzeni lat?
  \item Czy ocena gry i cena wpływają na sprzedaż?
  \item Ile gier dostępne jest w sklepie?
\end{itemize}
Dodatkowo raport ma postać uniwersalną, co oznacza, że przy odświeżeniu dostosowuje się on do zmian w danych i prezentuje aktualne wykresy i wyniki. Ostatnia data kompilacji: `r I(py$today)`.




\section{Ranking na pracownika miesiąca}

|       Ranking na pracownika miesiąca wyznaczony został na podstawie liczby sprzedanych przez pracownika egzemplarzy w danym miesiącu. Kwoty sprzedaży oraz wypożyczenia nie były brane pod uwagę. Poniżej możemy zobaczyć jak prezentował się ranking pracowników w każdym z ostatnich 6 miesięcy.
```{python rating, fig.cap="\\label{fig:rating} Dzienna i miesięczna analiza sprzedaży gier.", fig.align="center", fig.width = 10, fig.height = 5, results = "hide"}
sql = """SELECT MONTH(date) AS month,
        YEAR(date) AS year,
        CONCAT(first_name, ' ', last_name) AS full_name,
        COUNT(*) AS count
FROM sale
JOIN staff
USING (staff_id)
GROUP BY year, month, full_name
"""
df = query_to_df(sql)


def month_ranking_example(df, year = 2023, month = 5):
    df = df[df.month == month][df.year == year][:5].sort_values(by = 'count', ascending = True)
    return df
  
  
df1 = month_ranking_example(df, year = 2023, month = 5)
df2 = month_ranking_example(df, year = 2023, month = 4)
df3 = month_ranking_example(df, year = 2023, month = 3)
df4 = month_ranking_example(df, year = 2023, month = 2)
df5 = month_ranking_example(df, year = 2023, month = 1)
df6 = month_ranking_example(df, year = 2022, month = 12)


month_names = {1 : 'Styczeń',
                  2 : 'Luty',
                  3 : 'Marzec',
                  4 : 'Kwiecień',
                  5 : 'Maj',
                  6 : 'Czerwiec',
                  7 : 'Lipiec',
                  8 : 'Sierpień',
                  9 : 'Wrzesień', 
                  10 : 'Październik',
                  11 : 'Listopad', 
                  12 : 'Grudzień'}

plt.style.use('bmh')
fig, ax = plt.subplots(3, 2, figsize = (15, 10))
ax[0, 0].barh(df1['full_name'], df1['count'], color = ['skyblue', 'skyblue', 'sienna', 'silver', 'goldenrod'])
ax[1, 0].barh(df2['full_name'], df2['count'], color = ['skyblue', 'skyblue', 'sienna', 'silver', 'goldenrod'])
ax[2, 0].barh(df3['full_name'], df3['count'], color = ['skyblue', 'skyblue', 'sienna', 'silver', 'goldenrod'])
ax[0, 1].barh(df4['full_name'], df4['count'], color = ['skyblue', 'skyblue', 'sienna', 'silver', 'goldenrod'])
ax[1, 1].barh(df5['full_name'], df5['count'], color = ['skyblue', 'skyblue', 'sienna', 'silver', 'goldenrod'])
ax[2, 1].barh(df6['full_name'], df6['count'], color = ['skyblue', 'skyblue', 'sienna', 'silver', 'goldenrod'])

ax[0, 0].bar_label(ax[0, 0].containers[0], fmt= '%i', label_type='edge')
ax[0, 0].tick_params(axis='y', direction='in',pad=-15)
ax[0, 0].set_yticklabels(df6['full_name'], horizontalalignment = "left")
ax[1, 0].bar_label(ax[1, 0].containers[0], fmt= '%i', label_type='edge')
ax[1, 0].tick_params(axis='y', direction='in',pad=-15)
ax[1, 0].set_yticklabels(df6['full_name'], horizontalalignment = "left")
ax[2, 0].bar_label(ax[2, 0].containers[0], fmt= '%i', label_type='edge')
ax[2, 0].tick_params(axis='y', direction='in',pad=-15)
ax[2, 0].set_yticklabels(df6['full_name'], horizontalalignment = "left")
ax[0, 1].bar_label(ax[0, 1].containers[0], fmt= '%i', label_type='edge')
ax[0, 1].tick_params(axis='y', direction='in',pad=-15)
ax[0, 1].set_yticklabels(df6['full_name'], horizontalalignment = "left")
ax[1, 1].bar_label(ax[1, 1].containers[0], fmt= '%i', label_type='edge')
ax[1, 1].tick_params(axis='y', direction='in',pad=-15)
ax[1, 1].set_yticklabels(df6['full_name'], horizontalalignment = "left")
ax[2, 1].bar_label(ax[2, 1].containers[0], fmt= '%i', label_type='edge')
ax[2, 1].tick_params(axis='y', direction='in',pad=-15)
ax[2, 1].set_yticklabels(df6['full_name'], horizontalalignment = "left")

ax[0, 0].set_title(month_names[df1.month.values[0]] + ' ' + str(df1.year.values[0]), size = 10)
ax[1, 0].set_title(month_names[df2.month.values[0]] + ' ' + str(df2.year.values[0]), size = 10)
ax[2, 0].set_title(month_names[df3.month.values[0]] + ' ' + str(df3.year.values[0]), size = 10)
ax[0, 1].set_title(month_names[df4.month.values[0]] + ' ' + str(df4.year.values[0]), size = 10)
ax[1, 1].set_title(month_names[df5.month.values[0]] + ' ' + str(df5.year.values[0]), size = 10)
ax[2, 1].set_title(month_names[df6.month.values[0]] + ' ' + str(df6.year.values[0]), size = 10)
plt.show()
```
W ostatnim miesiącu pierwsze miejsce w rankingu zajął/zajęła ...




\section{Ranking zawodników turniejowych}

|       Ranking zawodników turniejów organizowanych przez sklep wyznaczany jest na podstawie miejsc, które uczestnik zajął we wszystkich zawodach organizowanych do tej pory. Dla danego zawodnika brane są pod uwagę tylko miejsca na podium. 1. miejsce daje 3 punkty, 2. miejsce 2 punkty, natomiast 3. daje 1 punkt. Wynikiem, na bazie którego kształtuje się ranking, jest suma punktów uzyskanych ze wszystkich dotychczasowych turniejów.




\section{Które gry przynoszą największy dochód ze sprzedaży, a które z wypożyczeń?}

|       Na podstawie dziennych sumarycznych dochodów ze sprzedaży jakie wygenerowała każda gra, został wyznaczony ranking najbardziej dochodowych gier.

```{python best_games_sales, fig.cap="\\label{fig:best_games_sales} Najbardziej dochodowe gry ze sprzedaży.", fig.align="center", fig.width = 14, fig.height = 10}

sql = """SELECT name, amount, date
FROM games_for_sale
JOIN sale
USING (game_id)"""

df3_sale = query_to_df(sql)

best5 = df3_sale.groupby('name').sum().sort_values(by = 'amount', ascending = False)[:5]
best5_timelapse = df3_sale[df3_sale.name.isin(best5.index) == True]
best5_timelapse = best5_timelapse.groupby(['name', 'date']).sum()

plt.style.use('bmh')
fig, ax = plt.subplots(figsize = (20, 7))
for game in best5.index:
    subgame = best5_timelapse.xs(game, level = 'name').cumsum()
    ax.step(subgame.index, subgame.amount, label = game)
ax.set_xlabel('Data')
ax.set_ylabel('Przychód')
ax.legend()
plt.show()
```

Podobnie tworzymy ranking dla dochodów z wypożyczeń.

```{python best_games_rent, fig.cap="\\label{fig:best_games_rent} Najbardziej dochodowe gry z wypożyczeń.", fig.align="center", fig.width = 14, fig.height = 10}

sql = """SELECT name, rent_price, rental_date, return_date
FROM games_to_rent
JOIN games_for_sale
USING (game_id)
JOIN rental
USING (item_id)"""

df3_rent = query_to_df(sql)

df3_rent['days'] = (df3_rent['return_date'] - df3_rent['rental_date']).dt.days
df3_rent['income'] = df3_rent['rent_price']*df3_rent['days']
df3_rent = df3_rent.drop(['rent_price', 'rental_date', 'days'], axis = 1)
best5_rent = df3_rent.groupby('name').sum().sort_values(by = 'income', ascending = False)[:5]
best5_rent_timelapse = df3_rent[df3_rent.name.isin(best5_rent.index) == True]
best5_rent_timelapse = best5_rent_timelapse.groupby(['name', 'return_date']).sum()

plt.style.use('bmh')
fig, ax = plt.subplots(figsize = (20, 7))
for game in best5_rent.index:
    subgame = best5_rent_timelapse.xs(game, level = 'name').cumsum()
    ax.step(subgame.index, subgame.income, label = game)
ax.set_xlabel('Data')
ax.set_ylabel('Przychód')
ax.legend()
plt.show()
```


\section{Które kategorie są najpopularniejsze?}

|       Aby odpowiedzić na to pytanie, zliczamy ile gier z danej kategorii sprzedało się od początku historii sklepu. Na tej podstawie tworzymy ranking kategorii, do której gry należące są najczęściej kupowane.

```{python categories_sales, fig.cap="\\label{fig:categories sales} Zestawienie najlepiej sprzedających się kategorii gier.", fig.align="center", fig.width = 10, fig.height = 8}

def best_categories(df):
    categories = df.category.values
    splitted = []
    for category in categories:
        category_split = category.split(', ')
        for indice in category_split:
            splitted.append(indice)
    splitted = np.array(splitted)
    splitted_series = pd.DataFrame(splitted)
    splitted_series.columns = ['Category']
    
    popularity = splitted_series.value_counts().reset_index()
    popularity.columns = ['Category', 'Count']
    first10 = popularity[:10]
    
    plt.style.use('bmh')
    fig, ax = plt.subplots(figsize = (11, 7))
    ax.bar(first10['Category'], first10['Count'], color = 'skyblue')
    ax.set_xticklabels(first10['Category'], rotation = 45)
    ax.set_ylabel('Number of games')
    plt.show()
    
    
    
    
sql = """SELECT category 
FROM games_for_sale 
JOIN sale 
USING (game_id)"""

df4_sale = query_to_df(sql)
ctgr_sale = best_categories(df4_sale)
ctgr_sale
```

To samo robimy, by wyznaczyć ranking najczęściej wypożyczanych gier, z tym że tutaj zliczamy wypożyczenia.

```{python categories_rental, fig.cap="\\label{fig:categories_rental} Zestawienie najlepiej wypożyczających się kategorii gier.", fig.align="center", fig.width = 10, fig.height = 8}

sql = """SELECT category
FROM games_for_sale
JOIN games_to_rent
USING (game_id)
JOIN rental
USING (item_id)"""

df4_rent = query_to_df(sql)
ctgr_rent = best_categories(df4_rent)
ctgr_rent
```


\section{Jak zmieniała się sprzedaż na przestrzeni lat?}

|       Tak jak widać na wykresie poniżej.

```{python sales, fig.cap="\\label{fig:sales} Dzienna i miesięczna analiza sprzedaży gier.", fig.align="center", fig.width = 8, fig.height = 5}

sql = """
SELECT SUM(amount) as amount, date, YEAR(date) AS year, MONTH(date) AS month
FROM games_for_sale
JOIN sale
USING (game_id)
GROUP BY date"""
df5 = query_to_df(sql)
df5 = df5.set_index('date')

sql2 = """SELECT SUM(amount) as amount, date, YEAR(date) AS year, MONTH(date) AS month
FROM games_for_sale
JOIN sale
USING (game_id)
GROUP BY year, month"""
df5_month = query_to_df(sql2)
df5_month = df5_month.set_index('date')

fig, ax = plt.subplots(2, 1, figsize = (20, 14))
ax[0].plot(df5.index, df5.amount, color = 'firebrick')
ax[1].plot(df5_month.index, df5_month.amount, color = 'firebrick')
ax[0].set_ylabel('Daily income')
ax[1].set_ylabel('Monthly income')
ax[1].set_xlabel('Date')
plt.show()
```


\section{Czy ocena gry i cena wpływają na sprzedaż?}

|       Aby ocenić zeleżność pomiędzy średnią oceną gry, a liczbą sprzedanych sztuk, możemy spojrzeć na wykres punktowy.

```{python rating_scatter, fig.cap="\\label{fig:rating_scatter} Wykres punktowy sprzedanych sztuk danej gry w zależności od jej średniej oceny.", fig.align="center", fig.width = 8, fig.height = 5}
sql = """
select s.game_id, g.name, g.avg_rating, g.price, count(*) as sale_count
from sale s
join games_for_sale g
  on s.game_id = g.game_id
where s.date > date_add(sysdate(), interval -12 month)
group by s.game_id, g.name, g.avg_rating, g.price
order by sale_count desc
"""
result = connection.execute(text(sql))
game_sale = pd.DataFrame(result.fetchall(), columns=result.keys())

cor_pearson = round(np.corrcoef(game_sale.avg_rating, game_sale.sale_count)[0, 1], 2)
cor_spearman = round(sp.spearmanr(game_sale.avg_rating, game_sale.sale_count)[0], 2)

plt.figure(figsize=(14, 8))
plt.scatter(game_sale.avg_rating, game_sale.sale_count)
plt.xlabel('Średnia ocena gry')
plt.ylabel('Liczba sprzedanych sztuk')
plt.show()
```

Współczynnik korelacji Pearsona wyniósł `r I(py$cor_pearson)`, natomiast współczynnik Spearmana jest równy `r I(py$cor_spearman)`.


Następnie dokładnie to samo wykonujemy dla ceny gry, aby ocenić, czy cena wpływa na sprzedaż.

```{python price_scatter, fig.cap="\\label{fig:price_scatter} Wykres punktowy sprzedanych sztuk danej gry w zależności od jej ceny.", fig.align="center", fig.width = 8, fig.height = 5}
cor_pearson = round(np.corrcoef(game_sale.price, game_sale.sale_count)[0, 1], 2)
cor_spearman = round(sp.spearmanr(game_sale.price, game_sale.sale_count)[0], 2)

plt.figure(figsize=(14, 8))
plt.scatter(game_sale.price, game_sale.sale_count)
plt.xlabel('Cena gry')
plt.ylabel('Liczba sprzedanych sztuk')
plt.show()
```

Współczynnik korelacji Pearsona wyniósł `r I(py$cor_pearson)`, natomiast współczynnik Spearmana jest równy `r I(py$cor_spearman)`.




\section{Ile gier dostępne jest w sklepie?}
Ostatnią rzeczą którą chcemy sprawdzić, jest podział gier na kategorie wiekowe i sprawdzenie liczności dla każdej z kategorii. Sugerowaliśmy się klasyfikacją gier PEGI, a kategorie są następujące:

\begin{itemize}
\item \textbf{Everyone} - gry przeznaczone dla każdego
\item \textbf{6+} - gry dla osób od 6 lat
\item \textbf{12+} - gry dla osób od 12 lat
\item \textbf{16+} - gry dla osób od 16 lat
\item \textbf{18+} - gry przeznaczone jedynie dla dorosłych.
\end{itemize}
Oczywiście każda kolejna kategoria nie zawiera się w poprzedniej, ani w następnej tzn. w kategorii gier \textbf{12+} nie ma gier z pozostałych kategorii wiekowych.
\newline
Liczność każdej kategorii możemy zaobserwować na poniższym wykresie słupkowym.
```{python age_bar, fig.cap="\\label{fig:age_bar} Ilość dostępnych gier w danych kategoriach wiekowych.", fig.align="center", fig.width = 10, fig.height = 5, results = "hide"}

sql = """
SELECT age, SUM(availability) AS availability
FROM games_for_sale
GROUP BY age
"""
df6 = query_to_df(sql)
df6 = df6.set_index('age')

pegi = pd.DataFrame(index = ['Everyone', '6+', '12+', '16+', '18+'],
                    data = [sum(df6[df6.index < 6].values),
                     sum(df6.loc[(df6.index >= 6) & (df6.index < 12)].values),
                     sum(df6.loc[(df6.index >= 12) & (df6.index < 16)].values),
                     sum(df6.loc[(df6.index >= 16) & (df6.index < 18)].values),
                     sum(df6[df6.index >= 18].values)],
                   columns = ['Number of games'])

              
plt.style.use('bmh')
fig, ax = plt.subplots(figsize = (12, 6))
ax.bar(pegi.index, pegi['Number of games'], color = ['lightgreen', 'lightgreen', 'gold', 'gold' , 'orangered'])
ax.set_xticklabels(pegi.index)
ax.set_ylabel('Number of games')
ax.bar_label(ax.containers[0], fmt= '%i', label_type='edge')
plt.show()
```




```{python}
connection.close()
```
